import fs from 'node:fs';
import path from 'node:path';
import { Project, SyntaxKind, SourceFile } from 'ts-morph';
import { REPO, sha } from './util.js';

export interface ModuleNode {
  file: string;            // repo-relative path
  hash: string;            // content hash (deterministic)
  exports: string[];       // "name: signature" — sorted
  imports: string[];       // raw specifiers — sorted
  edges: string[];         // repo-relative files this module depends on — sorted
}
export interface ModuleGraph { modules: ModuleNode[] }  // NO timestamps (A1.2)

function extractExports(sf: SourceFile): string[] {
  const out: string[] = [];
  for (const [name, decls] of sf.getExportedDeclarations()) {
    for (const d of decls) {
      const kind = d.getKind();
      try {
        if (kind === SyntaxKind.InterfaceDeclaration || kind === SyntaxKind.ClassDeclaration) {
          const members = (d as any).getProperties?.().map(
            (p: any) => `${p.getName()}: ${p.getType().getText()}`) ?? [];
          const methods = (d as any).getMethods?.().map(
            (m: any) => `${m.getName()}(${m.getParameters().map((x: any) => `${x.getName()}: ${x.getType().getText()}`).join(', ')}): ${m.getReturnType().getText()}`) ?? [];
          out.push(`${name} { ${[...members, ...methods].sort().join('; ')} }`);
        } else if (kind === SyntaxKind.FunctionDeclaration) {
          const f = d as any;
          out.push(`${name}(${f.getParameters().map((x: any) => `${x.getName()}: ${x.getType().getText()}`).join(', ')}): ${f.getReturnType().getText()}`);
        } else if (kind === SyntaxKind.TypeAliasDeclaration) {
          out.push(`${name} = ${(d as any).getType().getText()}`);
        } else {
          out.push(`${name}: ${(d as any).getType?.().getText() ?? 'unknown'}`);
        }
      } catch { out.push(name); }
    }
  }
  return [...new Set(out)].sort();
}

function extractEdges(sf: SourceFile): { imports: string[]; edges: string[] } {
  const imports: string[] = [];
  const edges: string[] = [];
  for (const i of sf.getImportDeclarations()) {
    imports.push(i.getModuleSpecifierValue());
    const target = i.getModuleSpecifierSourceFile();
    if (target && !target.getFilePath().includes('node_modules')) {
      edges.push(path.relative(REPO, target.getFilePath()));
    }
  }
  return { imports: [...new Set(imports)].sort(), edges: [...new Set(edges)].sort() };
}

/** Builds the module graph deterministically: sorted modules, sorted everything,
 *  no timestamps. Same code in -> same bytes out (checkpoint-safe, A1.2). */
export function buildGraph(): ModuleGraph {
  const tsconfig = path.join(REPO, 'tsconfig.json');
  if (!fs.existsSync(tsconfig)) return { modules: [] }; // degraded no-AST mode (O4)
  const project = new Project({ tsConfigFilePath: tsconfig, skipAddingFilesFromTsConfig: false });
  const modules: ModuleNode[] = [];
  for (const sf of project.getSourceFiles()) {
    const fp = sf.getFilePath();
    if (fp.includes('node_modules')) continue;
    const rel = path.relative(REPO, fp);
    const { imports, edges } = extractEdges(sf);
    modules.push({
      file: rel,
      hash: sha(fs.readFileSync(fp)),
      exports: extractExports(sf),
      imports,
      edges,
    });
  }
  modules.sort((a, b) => a.file.localeCompare(b.file));
  return { modules };
}

/** Reverse-edge lookup: which modules depend on `file` (transitively, 1 level). */
export function dependentsOf(g: ModuleGraph, file: string): string[] {
  return g.modules.filter((m) => m.edges.includes(file)).map((m) => m.file).sort();
}

/** Deterministic circular-dependency detection over the edge graph (DAG rule, 02a). */
export function findCycles(g: ModuleGraph): string[][] {
  const cycles: string[][] = [];
  const stack: string[] = [];
  const visited = new Set<string>();
  const inStack = new Set<string>();
  const byFile = new Map(g.modules.map((m) => [m.file, m]));
  const dfs = (f: string): void => {
    if (inStack.has(f)) {
      cycles.push([...stack.slice(stack.indexOf(f)), f]);
      return;
    }
    if (visited.has(f)) return;
    visited.add(f); inStack.add(f); stack.push(f);
    for (const e of byFile.get(f)?.edges ?? []) if (byFile.has(e)) dfs(e);
    stack.pop(); inStack.delete(f);
  };
  for (const m of g.modules) dfs(m.file);
  return cycles;
}

export function renderModuleMap(g: ModuleGraph): string {
  const lines = [
    '# Module Map',
    '<!-- GENERATED BY aegis ast build - DO NOT HAND-EDIT -->',
    '',
  ];
  for (const m of g.modules) {
    lines.push(`## ${m.file}`);
    lines.push(`- exports: ${m.exports.join(' | ') || '(none)'}`);
    lines.push(`- imports: ${m.imports.join(', ') || '(none)'}`);
    lines.push(`- depends on: ${m.edges.join(', ') || '(none)'}`);
    lines.push('');
  }
  return lines.join('\n');
}
