import fs from 'node:fs';
import path from 'node:path';
import { AEGIS_DIR, REPO, die, ok, readJ, writeJ } from '../lib/util.js';

/** aegis monitor --once - ONE monitoring pass, designed for cron/CI (08b).
 *  Aegis never runs on a timer; the scheduler is external.
 *  Targets come from .aegis/monitor-targets.json: [{url, benchmark_ms}]
 *  Exit 10 on threshold breach. UNMEASURED when no targets configured. */

interface Target { url: string; benchmark_ms?: number }
interface CheckResult { url: string; ok: boolean; status: number | string; latency_ms: number; breach: boolean }

export async function monitor(args: string[]): Promise<void> {
  if (!args.includes('--once')) die(2, 'usage: aegis monitor --once (scheduler is external: cron/CI)');
  const targetsP = path.join(AEGIS_DIR, 'monitor-targets.json');
  const reportDir = path.join(AEGIS_DIR, 'monitor');
  fs.mkdirSync(reportDir, { recursive: true });

  if (!fs.existsSync(targetsP)) {
    writeJ(path.join(reportDir, 'last-run.json'), { at: new Date().toISOString(), status: 'UNMEASURED', reason: 'no monitor-targets.json' });
    ok('monitor: UNMEASURED - no .aegis/monitor-targets.json (configure endpoints first)');
    return;
  }
  const targets = readJ<Target[]>(targetsP);
  const results: CheckResult[] = [];
  for (const t of targets) {
    const bench = t.benchmark_ms ?? 200;
    const start = Date.now();
    try {
      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), 10_000);
      const res = await fetch(t.url, { signal: ctrl.signal });
      clearTimeout(timer);
      const latency = Date.now() - start;
      results.push({ url: t.url, ok: res.ok, status: res.status, latency_ms: latency,
        breach: !res.ok || latency > bench * 2 });
    } catch (e: any) {
      results.push({ url: t.url, ok: false, status: 'unreachable', latency_ms: Date.now() - start, breach: true });
    }
  }
  const breaches = results.filter((r) => r.breach);
  const status = breaches.length ? 'BREACH' : 'HEALTHY';
  writeJ(path.join(reportDir, 'last-run.json'), { at: new Date().toISOString(), status, results });

  const brainDir = path.join(REPO, 'brain', 'quality');
  fs.mkdirSync(brainDir, { recursive: true });
  fs.writeFileSync(path.join(brainDir, 'post-ship-report.md'),
    ['# Post-Ship Monitor Report', '<!-- GENERATED BY aegis monitor --once - refreshed per run -->', '',
     `- status: **${status}**`, `- checks: ${results.length} | breaches: ${breaches.length}`, '',
     ...results.map((r) => `- ${r.url}: ${r.status} in ${r.latency_ms}ms ${r.breach ? '**BREACH**' : 'ok'}`), ''].join('\n'));

  if (breaches.length) die(10, `monitor: BREACH on ${breaches.length}/${results.length} targets`);
  ok(`monitor: HEALTHY - ${results.length} targets within thresholds`);
}
