import fs from 'node:fs';
import path from 'node:path';
import { AEGIS_DIR, REPO, ok, readJ } from '../lib/util.js';
import { loadState, loadConfig } from '../lib/state.js';

/** Phase 2: aegis sync - regenerate tool-native context files from brain truth.
 *  Deterministic: same brain in -> same bytes out. */
export function sync(): void {
  const ctxP = path.join(REPO, 'brain', 'context-window.md');
  const ctx = fs.existsSync(ctxP) ? fs.readFileSync(ctxP, 'utf8') : '# Context Window\n';
  const s = loadState();
  const cfg = loadConfig();
  const header = [
    '<!-- GENERATED BY aegis sync - DO NOT HAND-EDIT. Edit brain/ files instead. -->',
    '# Project Context (AEGIS)',
    '',
    `Current skill: ${s.current_skill} | Environment: ${cfg.environment_level} | Ship profile: ${cfg.ship_profile}`,
    '',
    'Rules: read brain/context-window.md before any edit; state changes only via `aegis` CLI; sacred gates are CLI-enforced.',
    '',
  ].join('\n');
  for (const name of ['AGENTS.md', 'CLAUDE.md']) {
    fs.writeFileSync(path.join(REPO, name), header + ctx);
  }
  ok('AGENTS.md + CLAUDE.md regenerated from brain');
}

/** Phase 2: aegis gc - checkpoint retention (O8: 20 sessions or 30 days) +
 *  archive resolved quality logs older than 90 days. */
export function gc(): void {
  const dir = path.join(AEGIS_DIR, 'checkpoints');
  const RETAIN_COUNT = 20;
  const RETAIN_MS = 30 * 24 * 3600 * 1000;
  if (!fs.existsSync(dir)) { ok('nothing to collect'); return; }
  const files = fs.readdirSync(dir).filter((f) => f.startsWith('cp-')).sort();
  const now = Date.now();
  const toDelete = files.filter((f, i) => {
    const ts = parseInt(f.replace('cp-', '').replace('.json', ''), 10);
    const tooOld = now - ts > RETAIN_MS;
    const beyondCount = i < files.length - RETAIN_COUNT;
    return tooOld || beyondCount;
  });
  for (const f of toDelete) fs.unlinkSync(path.join(dir, f));
  ok(`gc: ${toDelete.length} checkpoints archived/deleted, ${files.length - toDelete.length} retained (20/30-day policy)`);
}
