import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { performance } from 'node:perf_hooks';
import { AEGIS_DIR, REPO, die, ok, readJ, writeJ } from '../lib/util.js';
import { loadConfig, contractsPath } from '../lib/state.js';

/** aegis validate <suite> - real tool runners with measurement citations.
 *  Every result: {tool, command, status: PASS|FAIL|UNMEASURED, summary}.
 *  Brain reports are deterministic (no timestamps); machine JSON in .aegis
 *  carries timestamps (not checkpoint-hashed). Exit 9 on FAIL. */

export interface Result { suite: string; tool: string; command: string; status: 'PASS'|'FAIL'|'UNMEASURED'; summary: string }

function runCmd(command: string, cwd = REPO): { code: number; out: string } {
  try { return { code: 0, out: execSync(command, { cwd, encoding: 'utf8', stdio: 'pipe' }) }; }
  catch (e: any) { return { code: e.status ?? 1, out: String(e.stdout ?? '') + String(e.stderr ?? e.message) }; }
}

function record(r: Result): void {
  const dir = path.join(AEGIS_DIR, 'validation');
  fs.mkdirSync(dir, { recursive: true });
  writeJ(path.join(dir, `${r.suite}.json`), { ...r, at: new Date().toISOString() });
  const brainDir = path.join(REPO, 'brain', 'quality');
  fs.mkdirSync(brainDir, { recursive: true });
  fs.writeFileSync(path.join(brainDir, `validation-${r.suite}.md`),
    [`# Validation: ${r.suite}`, '<!-- GENERATED BY aegis validate - refreshed per run -->', '',
     `- tool: ${r.tool}`, `- command: \`${r.command}\``, `- status: **${r.status}**`, `- summary: ${r.summary}`, ''].join('\n'));
}

/** Perf budgets, written by SKILL-06d to .aegis/perf-budgets.json.
 *  Schema: {bundle_kb, api_p95_ms, db_query_ms, tti_ms, api_target_url?}. */
interface PerfBudgets {
  bundle_kb: number; api_p95_ms: number; db_query_ms: number; tti_ms: number;
  api_target_url?: string;
}
const DEFAULT_BUDGETS: PerfBudgets = { bundle_kb: 200, api_p95_ms: 200, db_query_ms: 50, tti_ms: 3000 };

function loadPerfBudgets(): { budgets: PerfBudgets; source: string } {
  const p = path.join(AEGIS_DIR, 'perf-budgets.json');
  if (!fs.existsSync(p))
    return { budgets: DEFAULT_BUDGETS, source: 'no .aegis/perf-budgets.json - default budgets (bundle 200kb, api p95 200ms, db 50ms, tti 3s)' };
  try {
    const j = readJ<Partial<PerfBudgets>>(p);
    return { budgets: { ...DEFAULT_BUDGETS, ...j }, source: 'budgets from .aegis/perf-budgets.json' };
  } catch {
    return { budgets: DEFAULT_BUDGETS, source: '.aegis/perf-budgets.json UNPARSEABLE - default budgets used' };
  }
}

/** p95 latency over n timed requests; null if any request fails (honest
 *  UNMEASURED rather than a partial sample dressed up as a measurement). */
async function measureApiP95(url: string, n = 20): Promise<number | null> {
  const times: number[] = [];
  for (let i = 0; i < n; i++) {
    const t0 = performance.now();
    try {
      const r = await fetch(url, { signal: AbortSignal.timeout(10_000) });
      await r.arrayBuffer();
    } catch { return null; }
    times.push(performance.now() - t0);
  }
  times.sort((a, b) => a - b);
  return times[Math.ceil(0.95 * times.length) - 1];
}

const suites: Record<string, () => Result | Promise<Result>> = {
  contracts: () => {
    const cp = contractsPath();
    const hasContracts = fs.existsSync(path.join(REPO, cp));
    const tscBin = fs.existsSync(path.join(REPO, 'node_modules', '.bin', 'tsc'))
      ? `"${path.join(REPO, 'node_modules', '.bin', 'tsc')}"` : 'tsc';
    const r = runCmd(`${tscBin} --noEmit`);
    return { suite: 'contracts', tool: 'tsc', command: `${tscBin} --noEmit`,
      status: !hasContracts ? 'UNMEASURED' : r.code === 0 ? 'PASS' : 'FAIL',
      summary: !hasContracts ? `no ${cp} - N1 not applicable yet`
        : r.code === 0 ? 'typecheck clean, contracts present' : r.out.split('\n').slice(0, 8).join(' | ') };
  },
  tests: () => {
    const pkgP = path.join(REPO, 'package.json');
    if (!fs.existsSync(pkgP))
      return { suite: 'tests', tool: 'npm', command: 'npm test', status: 'UNMEASURED', summary: 'no package.json - not an npm project' };
    const pkg = JSON.parse(fs.readFileSync(pkgP, 'utf8'));
    const script = pkg.scripts?.test;
    if (!script || script.includes('no test specified'))
      return { suite: 'tests', tool: 'npm', command: 'npm test', status: 'UNMEASURED', summary: 'no test script defined' };
    const r = runCmd('npm test');
    return { suite: 'tests', tool: 'npm', command: 'npm test',
      status: r.code === 0 ? 'PASS' : 'FAIL',
      summary: r.out.split('\n').filter(Boolean).slice(-3).join(' | ') || `exit ${r.code}, no output` };
  },
  deps: () => {
    // npm audit needs a lockfile; say so instead of "unparseable" (ENOLOCK).
    if (!['package-lock.json', 'npm-shrinkwrap.json'].some((f) => fs.existsSync(path.join(REPO, f))))
      return { suite: 'deps', tool: 'npm audit', command: 'npm audit --json', status: 'UNMEASURED',
        summary: 'no lockfile - run npm install first (npm audit requires package-lock.json)' };
    const r = runCmd('npm audit --json');
    try {
      const j = JSON.parse(r.out);
      const v = j.metadata?.vulnerabilities ?? {};
      const crit = (v.critical ?? 0) + (v.high ?? 0);
      return { suite: 'deps', tool: 'npm audit', command: 'npm audit --json',
        status: crit > 0 ? 'FAIL' : 'PASS',
        summary: `critical:${v.critical ?? 0} high:${v.high ?? 0} moderate:${v.moderate ?? 0} low:${v.low ?? 0}` };
    } catch {
      const cause = r.out.split('\n').filter(Boolean).slice(0, 3).join(' | ') || `exit ${r.code}, no output`;
      return { suite: 'deps', tool: 'npm audit', command: 'npm audit --json', status: 'UNMEASURED',
        summary: `audit output unparseable (exit ${r.code}): ${cause}` };
    }
  },
  perf: async () => {
    const { budgets, source } = loadPerfBudgets();
    const parts: string[] = [];
    let failed = false, measured = false;
    for (const dir of ['dist', 'build', '.next/static']) {
      const p = path.join(REPO, dir);
      if (!fs.existsSync(p)) continue;
      let js = 0;
      const walk = (d: string): void => { for (const f of fs.readdirSync(d)) { const fp = path.join(d, f);
        fs.statSync(fp).isDirectory() ? walk(fp) : (f.endsWith('.js') && (js += fs.statSync(fp).size)); } };
      walk(p);
      const kb = Math.round(js / 1024);
      measured = true;
      if (kb > budgets.bundle_kb) failed = true;
      parts.push(`JS bundle ${kb}kb vs ${budgets.bundle_kb}kb budget (${dir}) -> ${kb <= budgets.bundle_kb ? 'PASS' : 'FAIL'}`);
      break;
    }
    if (!measured) parts.push('bundle UNMEASURED - no dist/build/.next output (build first, or L0 static review only)');
    let apiCmd = '';
    if (budgets.api_target_url) {
      apiCmd = `; fetch x20 ${budgets.api_target_url}`;
      const p95 = await measureApiP95(budgets.api_target_url);
      if (p95 === null) parts.push(`API p95 UNMEASURED - ${budgets.api_target_url} unreachable`);
      else {
        measured = true;
        if (p95 > budgets.api_p95_ms) failed = true;
        parts.push(`API p95 ${Math.round(p95)}ms vs ${budgets.api_p95_ms}ms budget (20 requests) -> ${p95 <= budgets.api_p95_ms ? 'PASS' : 'FAIL'}`);
      }
    }
    // Not measurable without app-specific harnesses - said out loud, never guessed.
    parts.push(`db query ${budgets.db_query_ms}ms budget UNMEASURED - needs an app DB harness`);
    parts.push(`TTI ${budgets.tti_ms}ms budget UNMEASURED - needs a browser harness`);
    return { suite: 'perf',
      tool: budgets.api_target_url ? 'fs-measure+fetch' : 'fs-measure',
      command: `sum(js bytes in dist|build|.next)${apiCmd}`,
      status: failed ? 'FAIL' : measured ? 'PASS' : 'UNMEASURED',
      summary: `${parts.join('; ')} [${source}]` };
  },
  e2e: () => {
    const hasPw = fs.existsSync(path.join(REPO, 'playwright.config.ts')) || fs.existsSync(path.join(REPO, 'playwright.config.js'));
    if (!hasPw) return { suite: 'e2e', tool: 'playwright', command: 'npx playwright test', status: 'UNMEASURED', summary: 'no playwright config' };
    const r = runCmd('npx --no-install playwright test --reporter=line');
    return { suite: 'e2e', tool: 'playwright', command: 'npx playwright test',
      status: r.code === 0 ? 'PASS' : 'FAIL',
      summary: r.out.split('\n').filter(Boolean).slice(-3).join(' | ') || `exit ${r.code}, no output` };
  },
};

export const BUILTIN_SUITES = Object.keys(suites);

/** Custom suites from .aegis/config.json validate_suites (repo-owner-written
 *  smoke scripts: "run this, exit 0 = PASS"). Trusted input by design - the
 *  owner declares their own gates; the command string is recorded verbatim
 *  as the citation. Returns null when neither builtin nor custom exists. */
export async function runSuite(suite: string): Promise<Result | null> {
  if (suites[suite]) return suites[suite]();
  let custom: string | undefined;
  try { custom = loadConfig().validate_suites?.[suite]; } catch { custom = undefined; }
  if (!custom) return null;
  const r = runCmd(custom);
  return { suite, tool: 'custom', command: custom,
    status: r.code === 0 ? 'PASS' : 'FAIL',
    summary: r.out.split('\n').filter(Boolean).slice(-3).join(' | ') || `exit ${r.code}, no output` };
}

export async function validate(args: string[]): Promise<void> {
  const suite = args[0];
  const r = suite ? await runSuite(suite) : null;
  if (!r) {
    let custom: string[] = [];
    try { custom = Object.keys(loadConfig().validate_suites ?? {}); } catch { /* no config */ }
    die(2, `usage: aegis validate <${[...BUILTIN_SUITES, ...custom].join('|')}>`);
  }
  record(r);
  const line = `${r.suite}: ${r.status} - ${r.summary}`;
  if (r.status === 'FAIL') die(9, line);
  ok(line + (r.status === 'UNMEASURED' ? ' (honest skip - tool/env unavailable)' : ''));
}
