import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { AEGIS_DIR, REPO, die, ok, writeJ } from '../lib/util.js';

/** aegis validate <suite> - real tool runners with measurement citations.
 *  Every result: {tool, command, status: PASS|FAIL|UNMEASURED, summary}.
 *  Brain reports are deterministic (no timestamps); machine JSON in .aegis
 *  carries timestamps (not checkpoint-hashed). Exit 9 on FAIL. */

interface Result { suite: string; tool: string; command: string; status: 'PASS'|'FAIL'|'UNMEASURED'; summary: string }

function runCmd(command: string, cwd = REPO): { code: number; out: string } {
  try { return { code: 0, out: execSync(command, { cwd, encoding: 'utf8', stdio: 'pipe' }) }; }
  catch (e: any) { return { code: e.status ?? 1, out: String(e.stdout ?? '') + String(e.stderr ?? e.message) }; }
}

function record(r: Result): void {
  const dir = path.join(AEGIS_DIR, 'validation');
  fs.mkdirSync(dir, { recursive: true });
  writeJ(path.join(dir, `${r.suite}.json`), { ...r, at: new Date().toISOString() });
  const brainDir = path.join(REPO, 'brain', 'quality');
  fs.mkdirSync(brainDir, { recursive: true });
  fs.writeFileSync(path.join(brainDir, `validation-${r.suite}.md`),
    [`# Validation: ${r.suite}`, '<!-- GENERATED BY aegis validate - refreshed per run -->', '',
     `- tool: ${r.tool}`, `- command: \`${r.command}\``, `- status: **${r.status}**`, `- summary: ${r.summary}`, ''].join('\n'));
}

const suites: Record<string, () => Result> = {
  contracts: () => {
    const hasContracts = fs.existsSync(path.join(REPO, 'src', 'contracts'));
    const tscBin = fs.existsSync(path.join(REPO, 'node_modules', '.bin', 'tsc'))
      ? `"${path.join(REPO, 'node_modules', '.bin', 'tsc')}"` : 'tsc';
    const r = runCmd(`${tscBin} --noEmit`);
    return { suite: 'contracts', tool: 'tsc', command: `${tscBin} --noEmit`,
      status: !hasContracts ? 'UNMEASURED' : r.code === 0 ? 'PASS' : 'FAIL',
      summary: !hasContracts ? 'no src/contracts - N1 not applicable yet'
        : r.code === 0 ? 'typecheck clean, contracts present' : r.out.split('\n').slice(0, 8).join(' | ') };
  },
  tests: () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(REPO, 'package.json'), 'utf8'));
    const script = pkg.scripts?.test;
    if (!script || script.includes('no test specified'))
      return { suite: 'tests', tool: 'npm', command: 'npm test', status: 'UNMEASURED', summary: 'no test script defined' };
    const r = runCmd('npm test');
    return { suite: 'tests', tool: 'npm', command: 'npm test',
      status: r.code === 0 ? 'PASS' : 'FAIL',
      summary: r.out.split('\n').filter(Boolean).slice(-3).join(' | ') };
  },
  deps: () => {
    const r = runCmd('npm audit --json');
    try {
      const j = JSON.parse(r.out);
      const v = j.metadata?.vulnerabilities ?? {};
      const crit = (v.critical ?? 0) + (v.high ?? 0);
      return { suite: 'deps', tool: 'npm audit', command: 'npm audit --json',
        status: crit > 0 ? 'FAIL' : 'PASS',
        summary: `critical:${v.critical ?? 0} high:${v.high ?? 0} moderate:${v.moderate ?? 0} low:${v.low ?? 0}` };
    } catch { return { suite: 'deps', tool: 'npm audit', command: 'npm audit --json', status: 'UNMEASURED', summary: 'audit output unparseable' }; }
  },
  perf: () => {
    for (const dir of ['dist', 'build', '.next/static']) {
      const p = path.join(REPO, dir);
      if (!fs.existsSync(p)) continue;
      let js = 0;
      const walk = (d: string): void => { for (const f of fs.readdirSync(d)) { const fp = path.join(d, f);
        fs.statSync(fp).isDirectory() ? walk(fp) : (f.endsWith('.js') && (js += fs.statSync(fp).size)); } };
      walk(p);
      const kb = Math.round(js / 1024);
      return { suite: 'perf', tool: 'fs-measure', command: `sum(js bytes in ${dir})`,
        status: kb <= 200 ? 'PASS' : 'FAIL',
        summary: `JS bundle ${kb}kb vs 200kb budget (production profile)` };
    }
    return { suite: 'perf', tool: 'fs-measure', command: 'find dist|build|.next', status: 'UNMEASURED', summary: 'no build output found - build first, or L0 static review only' };
  },
  e2e: () => {
    const hasPw = fs.existsSync(path.join(REPO, 'playwright.config.ts')) || fs.existsSync(path.join(REPO, 'playwright.config.js'));
    if (!hasPw) return { suite: 'e2e', tool: 'playwright', command: 'npx playwright test', status: 'UNMEASURED', summary: 'no playwright config' };
    const r = runCmd('npx --no-install playwright test --reporter=line');
    return { suite: 'e2e', tool: 'playwright', command: 'npx playwright test',
      status: r.code === 0 ? 'PASS' : 'FAIL', summary: r.out.split('\n').filter(Boolean).slice(-3).join(' | ') };
  },
};

export function validate(args: string[]): void {
  const suite = args[0];
  if (!suite || !suites[suite])
    die(2, `usage: aegis validate <${Object.keys(suites).join('|')}>`);
  const r = suites[suite]();
  record(r);
  const line = `${r.suite}: ${r.status} - ${r.summary}`;
  if (r.status === 'FAIL') die(9, line);
  ok(line + (r.status === 'UNMEASURED' ? ' (honest skip - tool/env unavailable)' : ''));
}
