import fs from 'node:fs';
import path from 'node:path';
import { REPO, ok } from '../lib/util.js';
import { declaredApps, loadState } from '../lib/state.js';

/** aegis wave (v0.5.1): emit the executor prompt block for agent waves.
 *  External executors (opencode/GLM, fork agents) comply with Aegis only if
 *  the wave prompt tells them to - and prompts written from memory forget.
 *  This generates the exact block to paste into every wave prompt, tailored
 *  to the repo (name, pipeline position, declared apps), so compliance is
 *  an artifact, not a memory. Written to brain/wave-prompt.md (deterministic:
 *  brain/ is checkpoint-hashed, so NO timestamps - A1.2). */
export function wave(_args: string[]): void {
  const repo = path.basename(REPO);
  const apps = declaredApps();
  let skill = '00a';
  try { skill = loadState().current_skill; } catch { /* pre-init: still useful */ }
  const lines = [
    '<!-- GENERATED BY aegis wave - regenerate per session. Do not edit. -->',
    `# Wave Prompt Block - ${repo}`,
    '',
    'Paste this into every executor/wave prompt for this repo:',
    '',
    '```',
    `You are an executor working in the ${repo} repository, which uses Aegis`,
    'for enforcement. Rules you must follow:',
    '',
    '1. Orient first: read AGENTS.md, then run `aegis status` and `aegis next`',
    '   (add --app <name> if multi-app). If returning cold, read',
    '   brain/handoff.md if it exists.',
    '2. Record every command you run through the audit trail:',
    '     aegis exec -- <your command>',
    '   This checkpoints before/after and records your exit code. Unguarded',
    '   work is invisible work; `aegis doctor` drift detection will flag it.',
    '3. NEVER hand-edit .aegis/ files. State changes only via the aegis CLI.',
    '   Tampering is hash-detected (resume exit 6) and escalates to a human.',
    '4. Small fixes: `aegis fix start "<desc>"` before, `aegis fix done` after',
    '   (done refuses if the test suite is red). Docs/config: `aegis chore`.',
    '5. Do not approve gates, fake transitions, or bypass `aegis merge check`.',
    '   If you are blocked (exit 3/4/5/7), STOP and report the blocker with',
    '   the command output - do not route around it.',
    '6. Report once, at the end: what ran (cited), what passed, what is',
    '   UNMEASURED and why.',
    '```',
    '',
    `Current pipeline position: ${skill}${apps.length ? ` | apps: ${apps.join(', ')} (executors must pass --app)` : ''}`,
    '',
  ];
  const p = path.join(REPO, 'brain', 'wave-prompt.md');
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, lines.join('\n'));
  console.log(lines.join('\n'));
  ok('wave prompt block written to brain/wave-prompt.md - paste it into every executor prompt');
}
